services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin123'
      MYSQL_DATABASE: 'flask-diet'
      MYSQL_ROOT_PASSWORD: 'admin123'
    ports:
      - "3307:3306"
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - '/c/Users/kaua_/OneDrive/Área de Trabalho/daily-diet-data:/var/lib/mysql'